---
FEATURES:
  AerialRefuelling:
    keys:
      - designatorPrefix
      - designatorNumber
      - designatorSuffix
      - designatorDirection
    abbrev: ARF
    colour:
    label:
  AeronauticalGroundLight:
    keys:
      - type
      - name
    abbrev: AGL
    colour:
    label:
  AircraftGroundService:
    keys:
      - type
    abbrev: ACG
    colour:
    label:
  AircraftStand:
    keys:
      - designator
      - type
    abbrev: AST
    colour:
    label:
  AirportClearanceService:
    keys:
      - name
    abbrev: ACS
    colour:
    label:
  AirportHeliport:
    keys:
      - designator
    abbrev: AHP
    colour:
    label:
  AirportHeliportCollocation:
    keys:
    abbrev: AHC
    colour:
    label:
  AirportHotSpot:
    keys:
      - designator
    abbrev: AHT
    colour:
    label:
  AirportProtectionAreaMarking:
    keys:
    abbrev: APM
    colour:
    label:
  AirportSuppliesService:
    keys:
      - fuelSupply
      - oilSupply
      - nitrogenSupply
      - oxygenSupply
    abbrev: ASV
    colour:
    label:
  Airspace:
    keys:
      - designator
      - type
    abbrev: ASE
    colour:
    label:
  AirspaceBorderCrossing:
    keys:
    abbrev: ABC
    colour:
    label:
  AirTrafficControlService:
    keys:
      - location
      - type
    abbrev: ATC
    colour:
    label:
  AirTrafficManagementService:
    keys:
    abbrev: ATM
    colour:
    label:
  AltimeterSource:
    keys:
    abbrev: ALT
    colour:
    label:
  AngleIndication:
    keys:
    abbrev: AIN
    colour:
    label:
  ApproachLightingSystem:
    keys:
    abbrev: APL
    colour:
    label:
  Apron:
    keys:
      - name
    abbrev: APN
    colour:
    label:
  ApronElement:
    keys:
      - type
    abbrev: AEL
    colour:
    label:
  ApronLightSystem:
    keys:
      - color
    abbrev: ALS
    colour:
    label:
  ApronMarking:
    keys:
    abbrev: AMK
    colour:
    label:
  ArrestingGear:
    keys:
      - location
      - length
      - width
      - status
    abbrev: AGR
    colour:
    label:
  ArrivalLeg:
    keys:
      - length
    abbrev: ARL
    colour:
    label:
  ArrivalFeederLeg:
    keys:
      - length
    abbrev: AFL
    colour:
    label:
  AuthorityForAirspace:
    keys:
      - type
    abbrev: AFA
    colour:
    label:
  Azimuth:
    keys:
      - designator
      - type
    abbrev: AZM
    colour:
    label:
  ChangeOverPoint:
    keys:
    abbrev: COP
    colour:
    label:
  CheckpointINS:
    keys:
      - category
      - position
    abbrev: CNS
    colour:
    label:
  CheckpointVOR:
    keys:
      - category
      - position
    abbrev: CVO
    colour:
    label:
  CirclingArea:
    keys:
    abbrev: CIA
    colour:
    label:
  DeicingArea:
    keys:
    abbrev: DAA
    colour:
    label:
  DeicingAreaMarking:
    keys:
    abbrev: DAM
    colour:
    label:
  DepartureLeg:
    keys:
    abbrev: DLG
    colour:
    label:
  DesignatedPoint:
    keys:
      - designator
    abbrev: DPN
    colour:
    label:
  DirectionFinder:
    keys:
    abbrev: DFN
    colour:
    label:
  DistanceIndication:
    keys:
    abbrev: DIN
    colour:
    label:
  DME:
    keys:
      - type
      - designator
    abbrev: DME
    colour:
    label:
  Elevation:
    keys:
    abbrev: ELV
    colour:
    label:
  FinalLeg:
    keys:
    abbrev: FLG
    colour:
    label:
  FireFightingService:
    keys:
    abbrev: FFS
    colour:
    label:
  FlightRestriction:
    keys:
    abbrev: FRS
    colour:
    label:
  FloatingDockSite:
    keys:
    abbrev: FGD
    colour:
    label:
  GeoBorder:
    keys:
      - type
    abbrev: GBR
    colour:
    label:
  Glidepath:
    keys:
      - designator
    abbrev: GPT
    colour:
    label:
  GroundTrafficControlService:
    keys:
    abbrev: GTC
    colour:
    label:
  GuidanceLine:
    keys:
      - type
      - designator
    abbrev: GLN
    colour:
    label:
  GuidanceLineLightSystem:
    keys:
      - colour
    abbrev: GLL
    colour:
    label:
  GuidanceLineMarking:
    keys:
    abbrev: GLM
    colour:
    label:
  HoldingAssessment:
    keys:
    abbrev: HAS
    colour:
    label:
  HoldingPattern:
    keys:
    abbrev: HPT
    colour:
    label:
  InformationService:
    keys:
    abbrev: ISV
    colour:
    label:
  InitialLeg:
    keys:
    abbrev: ILG
    colour:
    label:
  InstrumentApproachProcedure:
    keys:
    abbrev: IAP
    colour:
    label:
  IntermediateLeg:
    keys:
    abbrev: INL
    colour:
    label:
  Localizer:
    keys:
      - designator
    abbrev: LLZ
    colour:
    label:
  MarkerBeacon:
    keys:
      - designator
    abbrev: MBC
    colour:
    label:
  MarkingBuoy:
    keys:
      - type
      - designator
    abbrev: MKB
    colour:
    label:
  MissedApproachLeg:
    keys:
    abbrev: MAL
    colour:
    label:
  Navaid:
    keys:
      - type
      - designator
    abbrev: NAV
    colour:
    label:
  NavigationArea:
    keys:
      - navigationAreaType
      - sector
    abbrev: NAA
    colour:
    label:
  NavigationAreaRestriction:
    keys:
      - type
    abbrev: NAN
    colour:
    label:
  NDB:
    keys:
      - keys
    abbrev: NDB
    colour:
    label:
  NonMovementArea:
    keys:
    abbrev: NMA
    colour:
    label:
  ObstacleArea:
    keys:
    abbrev: OAR
    colour:
    label:
  OrganisationAuthority:
    keys:
      - name
    abbrev: ORG
    colour:
    label:
  PassengerLoadingBridge:
    keys:
    abbrev: PLB
    colour:
    label:
  PassengerService:
    keys:
    abbrev: PSV
    colour:
    label:
  PilotControlledLighting:
    keys:
    abbrev: PCG
    colour:
    label:
  PrecisionApproachRadar:
    keys:
    abbrev: PAR
    colour:
    label:
  PrimarySurveillanceRadar:
    keys:
      - location
    abbrev: PSR
    colour:
    label:
  ProcedureDME:
    keys:
    abbrev: PDM
    colour:
    label:
  RadioCommunicationChannel:
    keys:
    abbrev: RCC
    colour:
    label:
  RadioFrequencyArea:
    keys:
      - type
    abbrev: RFA
    colour:
    label:
  Road:
    keys:
      - designator
    abbrev: ROA
    colour:
    label:
  Route:
    keys:
      - designatorPrefix
      - designatorNumber
      - designatorSecondLetter
      - type
    abbrev: RTE
    colour:
    label:
  RouteDME:
    keys:
    abbrev: RDM
    colour:
    label:
  RouteSegment:
    keys:
    abbrev: RSG
    colour:
    label:
  RulesProcedures:
    keys:
    abbrev: RUP
    colour:
    label:
  Runway:
    keys:
      - designator
      - type
    abbrev: RWY
    colour:
    label:
  RunwayBlastPad:
    keys:
    abbrev: RBP
    colour:
    label:
  RunwayCentrelinePoint:
    keys:
      - designator
    abbrev: RCP
    colour:
    label:
  RunwayDirection:
    keys:
      - designator
    abbrev: RDN
    colour:
    label:
  RunwayDirectionLightSystem:
    keys:
    abbrev: RLS
    colour:
    label:
  RunwayElement:
    keys:
    abbrev: REL
    colour:
    label:
  RunwayMarking:
    keys:
    abbrev: RMG
    colour:
    label:
  RunwayProtectArea:
    keys:
      - type
    abbrev: RPA
    colour:
    label:
  RunwayProtectAreaLightSystem:
    keys:
    abbrev: RPL
    colour:
    label:
  RunwayVisualRange:
    keys:
    abbrev: RVR
    colour:
    label:
  SafeAltitudeArea:
    keys:
    abbrev: SAA
    colour:
    label:
  SDF:
    keys:
      - designator
    abbrev: SDF
    colour:
    label:
  SeaplaneLandingArea:
    keys:
    abbrev: SLA
    colour:
    label:
  SeaplaneRampSite:
    keys:
    abbrev: SPR
    colour:
    label:
  SearchRescueService:
    keys:
      - type
    abbrev: SRE
    colour:
    label:
  SecondarySurveillanceRadar:
    keys:
    abbrev: SSV
    colour:
    label:
  SignificantPointInAirspace:
    keys:
    abbrev: SPA
    colour:
    label:
  SpecialDate:
    keys:
    abbrev: SPD
    colour:
    label:
  SpecialNavigationStation:
    keys:
    abbrev: SNS
    colour:
    label:
  SpecialNavigationSystem:
    keys:
      - designator
      - type
    abbrev: SNY
    colour:
    label:
  StandardInstrumentArrival:
    keys:
      - designator
    abbrev: SIA
    colour:
    label:
  StandardInstrumentDeparture:
    keys:
      - designator
    abbrev: SID
    colour:
    label:
  StandardLevelColumn:
    keys:
    abbrev: SLC
    colour:
    label:
  StandardLevelSector:
    keys:
    abbrev: SLS
    colour:
    label:
  StandardLevelTable:
    keys:
    abbrev: SLB
    colour:
    label:
  StandMarking:
    keys:
    abbrev: SMK
    colour:
    label:
  SurveyControlPoint:
    keys:
      - designator
    abbrev: SCP
    colour:
    label:
  TACAN:
    keys:
      - designator
    abbrev: TCN
    colour:
    label:
  TaxiHoldingPosition:
    keys:
    abbrev: THP
    colour:
    label:
  TaxiHoldingPositionLightSystem:
    keys:
    abbrev: THL
    colour:
    label:
  TaxiHoldingPositionMarking:
    keys:
    abbrev: THM
    colour:
    label:
  Taxiway:
    keys:
      - designator
      - type
    abbrev: TWY
    colour:
    label:
  TaxiwayElement:
    keys:
      - type
    abbrev: TWE
    colour:
    label:
  TaxiwayLightSystem:
    keys:
      - colour
    abbrev: TWL
    colour:
    label:
  TaxiwayMarking:
    keys:
    abbrev: TWM
    colour:
    label:
  TerminalArrivalArea:
    keys:
    abbrev: TAA
    colour:
    label:
  TouchDownLiftOff:
    keys:
      - designator
    abbrev: TLA
    colour:
    label:
  TouchDownLiftOffLightSystem:
    keys:
    abbrev: TLS
    colour:
    label:
  TouchDownLiftOffMarking:
    keys:
    abbrev: TLM
    colour:
    label:
  TouchDownLiftOffSafeArea:
    keys:
    abbrev: TSA
    colour:
    label:
  Unit:
    keys:
      - designator
      - type
    abbrev: UNI
    colour:
    label:
  UnplannedHolding:
    keys:
    abbrev: UHG
    colour:
    label:
  VerticalStructure:
    keys:
    abbrev: VST
    colour:
    label:
  VisualGlideSlopeIndicator:
    keys:
      - type
    abbrev: VGI
    colour:
    label:
  VOR:
    keys:
      - designator
      - type
    abbrev: VOR
    colour:
    label:
  WorkArea:
    keys:
    abbrev: WAR
    colour:
    label:
