---
FEATURES:
  AerialRefuelling:
    keys:
    abbrev:
    color:
  AeronauticalGroundLight:
    keys:
    abbrev:
    color:
  AircraftGroundService:
    keys:
    abbrev:
    color:
  AircraftStand:
    keys:
    abbrev:
    color:
  AirportClearanceService:
    keys:
    abbrev:
    color:
  AirportHeliport:
    keys:
      - designator
    abbrev: AHP
    color:
  AirportHeliportCollocation:
    keys:
    abbrev:
    color:
  AirportHotSpot:
    keys:
    abbrev:
    color:
  AirportProtectionAreaMarking:
    keys:
    abbrev:
    color:
  AirportSuppliesService:
    keys:
    abbrev:
    color:
  Airspace:
    keys:
    abbrev:
    color:
  AirspaceBorderCrossing:
    keys:
    abbrev:
    color:
  AirTrafficControlService:
    keys:
    abbrev:
    color:
  AirTrafficManagementService:
    keys:
    abbrev:
    color:
  AltimeterSource:
    keys:
    abbrev:
    color:
  AngleIndication:
    keys:
    abbrev:
    color:
  ApproachLightingSystem:
    keys:
    abbrev:
    color:
  Apron:
    keys:
    abbrev:
    color:
  ApronElement:
    keys:
    abbrev:
    color:
  ApronLightSystem:
    keys:
    abbrev:
    color:
  ApronMarking:
    keys:
    abbrev:
    color:
  ArrestingGear:
    keys:
    abbrev:
    color:
  ArrivalLeg:
    keys:
    abbrev:
    color:
  ArrivalFeederLeg:
    keys:
    abbrev:
    color:
  AuthorityForAirspace:
    keys:
    abbrev:
    color:
  Azimuth:
    keys:
    abbrev:
    color:
  ChangeOverPoint:
    keys:
    abbrev:
    color:
  CheckpointINS:
    keys:
    abbrev:
    color:
  CheckpointVOR:
    keys:
    abbrev:
    color:
  CirclingArea:
    keys:
    abbrev:
    color:
  DeicingArea:
    keys:
    abbrev:
    color:
  DeicingAreaMarking:
    keys:
    abbrev:
    color:
  DepartureLeg:
    keys:
    abbrev:
    color:
  DesignatedPoint:
    keys:
      - designator
    abbrev: DPN
    color:
  DirectionFinder:
    keys:
    abbrev:
    color:
  DistanceIndication:
    keys:
    abbrev:
    color:
  DME:
    keys:
    abbrev:
    color:
  Elevation:
    keys:
    abbrev:
    color:
  FinalLeg:
    keys:
    abbrev:
    color:
  FireFightingService:
    keys:
    abbrev:
    color:
  FlightRestriction:
    keys:
    abbrev:
    color:
  FloatingDockSite:
    keys:
    abbrev:
    color:
  GeoBorder:
    keys:
    abbrev:
    color:
  Glidepath:
    keys:
    abbrev:
    color:
  GroundTrafficControlService:
    keys:
    abbrev:
    color:
  GuidanceLine:
    keys:
    abbrev:
    color:
  GuidanceLineLightSystem:
    keys:
    abbrev:
    color:
  GuidanceLineMarking:
    keys:
    abbrev:
    color:
  HoldingAssessment:
    keys:
    abbrev:
    color:
  HoldingPattern:
    keys:
    abbrev:
    color:
  InformationService:
    keys:
    abbrev:
    color:
  InitialLeg:
    keys:
    abbrev:
    color:
  InstrumentApproachProcedure:
    keys:
    abbrev:
    color:
  IntermediateLeg:
    keys:
    abbrev:
    color:
  Localizer:
    keys:
    abbrev:
    color:
  MarkerBeacon:
    keys:
    abbrev:
    color:
  MarkingBuoy:
    keys:
    abbrev:
    color:
  MissedApproachLeg:
    keys:
    abbrev:
    color:
  Navaid:
    keys:
      - type
      - designator
    abbrev: NAV
    color:
  NavigationArea:
    keys:
    abbrev:
    color:
  NavigationAreaRestriction:
    keys:
    abbrev:
    color:
  NDB:
    keys:
    abbrev:
    color:
  NonMovementArea:
    keys:
    abbrev:
    color:
  ObstacleArea:
    keys:
    abbrev:
    color:
  OrganisationAuthority:
    keys:
      - name
    abbrev: ORG
    color:
  PassengerLoadingBridge:
    keys:
    abbrev:
    color:
  PassengerService:
    keys:
    abbrev:
    color:
  PilotControlledLighting:
    keys:
    abbrev:
    color:
  PrecisionApproachRadar:
    keys:
    abbrev:
    color:
  PrimarySurveillanceRadar:
    keys:
    abbrev:
    color:
  ProcedureDME:
    keys:
    abbrev:
    color:
  RadioCommunicationChannel:
    keys:
    abbrev:
    color:
  RadioFrequencyArea:
    keys:
    abbrev:
    color:
  Road:
    keys:
    abbrev:
    color:
  Route:
    keys:
    abbrev:
    color:
  RouteDME:
    keys:
    abbrev:
    color:
  RouteSegment:
    keys:
    abbrev: RSG
    color:
  RulesProcedures:
    keys:
    abbrev:
    color:
  Runway:
    keys:
      - designator
      - type
    abbrev: RWY
    color:
  RunwayBlastPad:
    keys:
    abbrev:
    color:
  RunwayCentrelinePoint:
    keys:
    abbrev:
    color:
  RunwayDirection:
    keys:
      - designator
    abbrev: RDN
    color:
  RunwayDirectionLightSystem:
    keys:
    abbrev:
    color:
  RunwayElement:
    keys:
    abbrev:
    color:
  RunwayMarking:
    keys:
    abbrev:
    color:
  RunwayProtectArea:
    keys:
    abbrev:
    color:
  RunwayProtectAreaLightSystem:
    keys:
    abbrev:
    color:
  RunwayVisualRange:
    keys:
    abbrev:
    color:
  SafeAltitudeArea:
    keys:
    abbrev:
    color:
  SDF:
    keys:
    abbrev:
    color:
  SeaplaneLandingArea:
    keys:
    abbrev:
    color:
  SeaplaneRampSite:
    keys:
    abbrev:
    color:
  SearchRescueService:
    keys:
    abbrev:
    color:
  SecondarySurveillanceRadar:
    keys:
    abbrev:
    color:
  SignificantPointInAirspace:
    keys:
    abbrev:
    color:
  SpecialDate:
    keys:
    abbrev:
    color:
  SpecialNavigationStation:
    keys:
    abbrev:
    color:
  SpecialNavigationSystem:
    keys:
    abbrev:
    color:
  StandardInstrumentArrival:
    keys:
    abbrev:
    color:
  StandardInstrumentDeparture:
    keys:
    abbrev:
    color:
  StandardLevelColumn:
    keys:
    abbrev:
    color:
  StandardLevelSector:
    keys:
    abbrev:
    color:
  StandardLevelTable:
    keys:
    abbrev:
    color:
  StandMarking:
    keys:
    abbrev:
    color:
  SurveyControlPoint:
    keys:
    abbrev:
    color:
  TACAN:
    keys:
    abbrev:
    color:
  TaxiHoldingPosition:
    keys:
    abbrev:
    color:
  TaxiHoldingPositionLightSystem:
    keys:
    abbrev:
    color:
  TaxiHoldingPositionMarking:
    keys:
    abbrev:
    color:
  Taxiway:
    keys:
    abbrev:
    color:
  TaxiwayElement:
    keys:
    abbrev:
    color:
  TaxiwayLightSystem:
    keys:
    abbrev:
    color:
  TaxiwayMarking:
    keys:
    abbrev:
    color:
  TerminalArrivalArea:
    keys:
    abbrev:
    color:
  TouchDownLiftOff:
    keys:
    abbrev:
    color:
  TouchDownLiftOffLightSystem:
    keys:
    abbrev:
    color:
  TouchDownLiftOffMarking:
    keys:
    abbrev:
    color:
  TouchDownLiftOffSafeArea:
    keys:
    abbrev:
    color:
  Unit:
    keys:
    abbrev:
    color:
  UnplannedHolding:
    keys:
    abbrev:
    color:
  VerticalStructure:
    keys:
    abbrev:
    color:
  VisualGlideSlopeIndicator:
    keys:
    abbrev:
    color:
  VOR:
    keys:
    abbrev:
    color:
  WorkArea:
    keys:
    abbrev:
    color:
#
#    AerialRefuelling:
#      keys:
#      targets:
#        InformationService:
#          xpath: "./aixm:"
#        AirTrafficControlService:
#          xpath: "./aixm:"
#        AirTrafficManagementService:
#          xpath: "./aixm:"
#    AircraftStand:
#      keys:
#      targets:
#        GuidanceLine:
#          xpath: "./aixm:"
#        Road:
#          xpath: "./aixm:"
#        DeicingArea:
#          xpath: "./aixm:"
#        PassengerLoadingBridge:
#          xpath: "./aixm:"
#        StandMarking:
#          xpath: "./aixm:"
#    AirportHeliport:
#      keys:
#      targets:
#        Runway:
#          xpath: "./aixm:associatedAirportHeliport"
#        Taxiway:
#          xpath: "./aixm:associatedAirportHeliport"
#        Apron:
#          xpath: "./aixm:"
#        Road:
#          xpath: "./aixm:"
#        TouchDownLiftOff:
#          xpath: "./aixm:"
#        WorkArea:
#          xpath: "./aixm:"
#        SurveyControlPoint:
#          xpath: "./aixm:"
#        NonMovementArea:
#          xpath: "./aixm:"
#        AirportHeliportCollocation:
#          xpath: "./aixm:"
#        AirportHotSpot:
#          xpath: "./aixm:"
#        RadarSystem:
#          xpath: "./aixm:"
#        InformationService:
#          xpath: "./aixm:"
#        GroundTrafficControlService:
#          xpath: "./aixm:"
#        AirTrafficControlService:
#          xpath: "./aixm:"
#        AirportGroundService:
#          xpath: "./aixm:"
#        AngleIndication:
#          xpath: "./aixm:"
#        DistanceIndication:
#          xpath: "./aixm:"
#        Navaid:
#          xpath: "./aixm:"
#        NavigationSystemCheckpoint:
#          xpath: "./aixm:"
#        DesignatedPoint:
#          xpath: "./aixm:"
#        SignificantPointInAirspace:
#          xpath: "./aixm:"
#        AeronauticalGroundLight:
#          xpath: "./aixm:"
#        Unit:
#          xpath: "./aixm:"
#        ObstacleArea:
#          xpath: "./aixm:"
#        TerminalArrivalArea:
#          xpath: "./aixm:"
#        NavigationArea:
#          xpath: "./aixm:"
#        Procedure:
#          xpath: "./aixm:"
#        FinalLeg:
#          xpath: "./aixm:"
#        SafeAltitudeArea:
#          xpath: "./aixm:"
#        ChangeOverPoint:
#          xpath: "./aixm:"
#        RulesProcedures:
#          xpath: "./aixm:"
#    AirportHeliportProtectionArea:
#      keys:
#      targets:
#        AirportProtectionAreaMarking:
#          xpath: "./aixm:"
#    AirportSuppliesService:
#      keys:
#      targets:
#        ApronElement:
#          xpath: "./aixm:"
#    Airspace:
#      keys:
#      targets:
#        AuthorityForAirspace:
#          xpath: "./aixm:"
#        StandardLevelSector:
#          xpath: "./aixm:"
#        InformationService:
#          xpath: "./aixm:"
#        AirTrafficControlService:
#          xpath: "./aixm:"
#        AirTrafficManagementService:
#          xpath: "./aixm:"
#        SearchRescueService:
#          xpath: "./aixm:"
#        SignificantPointInAirspace:
#          xpath: "./aixm:"
#        AirspaceBorderCrossing:
#          xpath: "./aixm:"
#        AerialRefuelling:
#          xpath: "./aixm:"
#        RulesProcedures:
#          xpath: "./aixm:"
#    AltimeterSource:
#      keys:
#      targets:
#        AirportHeliport:
#          xpath: "./aixm:"
#    AngleIndication:
#      keys:
#      targets:
#        SegmentLeg:
#          xpath: "./aixm:"
#    Apron:
#      keys:
#      targets:
#        GuidanceLine:
#          xpath: "./aixm:"
#        ApronElement:
#          xpath: "./aixm:"
#        DeicingArea:
#          xpath: "./aixm:"
#        ApronLightSystem:
#          xpath: "./aixm:"
#        ApronMarking:
#          xpath: "./aixm:"
#    ApronElement:
#      keys:
#      targets:
#        AircraftStand:
#          xpath: "./aixm:"
#    DME:
#      keys:
#      targets:
#        ProcedureDME:
#          xpath: "./aixm:"
#        RouteDME:
#          xpath: "./aixm:"
#    DeicingArea:
#      keys:
#      targets:
#        DeicingAreaMarking:
#          xpath: "./aixm:"
#    DesignatedPoint:
#      keys:
#      targets:
#        AngleIndication:
#          xpath: "./aixm:"
#        DistanceIndication:
#          xpath: "./aixm:"
#        SignificantPointInAirspace:
#          xpath: "./aixm:"
#        TerminalArrivalArea:
#          xpath: "./aixm:"
#        NavigationArea:
#          xpath: "./aixm:"
#        FinalLeg:
#          xpath: "./aixm:"
#        SafeAltitudeArea:
#          xpath: "./aixm:"
#        ChangeOverPoint:
#          xpath: "./aixm:"
#    DirectionFinder:
#      keys:
#      targets:
#        AirTrafficControlService:
#          xpath: "./aixm:"
#    DistanceIndication:
#      keys:
#      targets:
#        SegmentLeg:
#          xpath: "./aixm:"
#    FloatingDockSite:
#      keys:
#      targets:
#        SeaplaneLandingArea:
#          xpath: "./aixm:"
#    GroundLightSystem:
#      keys:
#      targets:
#        PilotControlledLighting:
#          xpath: "./aixm:"
#        VerticalStructure:
#          xpath: "./aixm:"
#    GuidanceLine:
#      keys:
#      targets:
#        TaxiHoldingPosition:
#          xpath: "./aixm:"
#        GuidanceLineLightSystem:
#          xpath: "./aixm:"
#        GuidanceLineMarking:
#          xpath: "./aixm:"
#    HoldingPattern:
#      keys:
#      targets:
#        HoldingAssessment:
#          xpath: "./aixm:"
#        InformationService:
#          xpath: "./aixm:"
#        AirTrafficControlService:
#          xpath: "./aixm:"
#    InformationService:
#      keys:
#      targets:
#        DirectionFinder:
#          xpath: "./aixm:"
#    InstrumentApproachProcedure:
#      keys:
#      targets:
#        CirclingArea:
#          xpath: "./aixm:"
#        TerminalArrivalArea:
#          xpath: "./aixm:"
#        ApproachLeg:
#          xpath: "./aixm:"
#    MarkerBeacon:
#      keys:
#      targets:
#        VerticalStructure:
#          xpath: "./aixm:"
#    Navaid:
#      keys:
#      targets:
#        AngleIndication:
#          xpath: "./aixm:"
#        DistanceIndication:
#          xpath: "./aixm:"
#        SignificantPointInAirspace:
#          xpath: "./aixm:"
#        TerminalArrivalArea:
#          xpath: "./aixm:"
#        NavigationArea:
#          xpath: "./aixm:"
#        Procedure:
#          xpath: "./aixm:"
#        FinalLeg:
#          xpath: "./aixm:"
#        SafeAltitudeArea:
#          xpath: "./aixm:"
#        ChangeOverPoint:
#          xpath: "./aixm:"
#    NavaidEquipment:
#      keys:
#      targets:
#        RadioFrequencyArea:
#          xpath: "./aixm:"
#        VerticalStructure:
#          xpath: "./aixm:"
#    OrganisationAuthority:
#      keys:
#      targets:
#        AuthorityForAirspace:
#          xpath: "./aixm:"
#        RadarSystem:
#          xpath: "./aixm:"
#        SpecialDate:
#          xpath: "./aixm:"
#        Unit:
#          xpath: "./aixm:"
#        ObstacleArea:
#          xpath: "./aixm:"
#        VerticalStructure:
#          xpath: "./aixm:"
#        Route:
#          xpath: "./aixm:"
#    PassengerService:
#      keys:
#      targets:
#        VerticalStructure:
#          xpath: "./aixm:"
#    PrecisionApproachRadar:
#      keys:
#      targets:
#        RadioFrequencyArea:
#          xpath: "./aixm:"
#    Procedure:
#      keys:
#      targets:
#        InformationService:
#          xpath: "./aixm:"
#        AirTrafficControlService:
#          xpath: "./aixm:"
#        NavigationAreaRestriction:
#          xpath: "./aixm:"
#    RadarSystem:
#      keys:
#      targets:
#        Procedure:
#          xpath: "./aixm:"
#    RadioCommunicationChannel:
#      keys:
#      targets:
#        RadioFrequencyArea:
#          xpath: "./aixm:"
#        Service:
#          xpath: "./aixm:"
#    Route:
#      keys:
#      targets:
#        Airspace:
#          xpath: "./aixm:"
#        RouteSegment:
#          xpath: "./aixm:routeFormed"
#    Runway:
#      keys:
#      targets:
#        RunwayDirection:
#          xpath: "./aixm:"
#        RunwayElement:
#          xpath: "./aixm:"
#        TaxiHoldingPosition:
#          xpath: "./aixm:"
#        TouchDownLiftOff:
#          xpath: "./aixm:"
#        RunwayMarking:
#          xpath: "./aixm:"
#        RadarSystem:
#          xpath: "./aixm:"
#    RunwayCentrelinePoint:
#      keys:
#      targets:
#        GuidanceLine:
#          xpath: "./aixm:"
#        AngleIndication:
#          xpath: "./aixm:"
#        DistanceIndication:
#          xpath: "./aixm:"
#        DesignatedPoint:
#          xpath: "./aixm:"
#        SignificantPointInAirspace:
#          xpath: "./aixm:"
#        TerminalArrivalArea:
#          xpath: "./aixm:"
#        NavigationArea:
#          xpath: "./aixm:"
#        FinalLeg:
#          xpath: "./aixm:"
#        SafeAltitudeArea:
#          xpath: "./aixm:"
#        ChangeOverPoint:
#          xpath: "./aixm:"
#    RunwayDirection:
#      keys:
#      targets:
#        RunwayProtectArea:
#          xpath: "./aixm:"
#        RunwayCentrelinePoint:
#          xpath: "./aixm:"
#        ArrestingGear:
#          xpath: "./aixm:"
#        VisualGlideSlopeIndicator:
#          xpath: "./aixm:"
#        RunwayVisualRange:
#          xpath: "./aixm:"
#        RunwayBlastPad:
#          xpath: "./aixm:"
#        RunwayDirectionLightSystem:
#          xpath: "./aixm:"
#        ApproachLightingSystem:
#          xpath: "./aixm:"
#        Navaid:
#          xpath: "./aixm:"
#        ObstacleArea:
#          xpath: "./aixm:"
#    RunwayElement:
#      keys:
#      targets:
#        RunwayDirection:
#          xpath: "./aixm:"
#    RunwayProtectArea:
#      keys:
#      targets:
#        RunwayProtectAreaLightSystem:
#          xpath: "./aixm:"
#    SafeAltitudeArea:
#      keys:
#      targets:
#        Procedure:
#          xpath: "./aixm:"
#    SeaplaneLandingArea:
#      keys:
#      targets:
#        MarkingBuoy:
#          xpath: "./aixm:"
#    SeaplaneRampSite:
#      keys:
#      targets:
#        SeaplaneLandingArea:
#          xpath: "./aixm:"
#    SecondarySurveillanceRadar:
#      keys:
#      targets:
#        RadioFrequencyArea:
#          xpath: "./aixm:"
#    SegmentLeg:
#      keys:
#      targets:
#        ProcedureDME:
#          xpath: "./aixm:"
#    Service:
#      keys:
#      targets:
#        VerticalStructure:
#          xpath: "./aixm:"
#    SpecialNavigationStation:
#      keys:
#      targets:
#        RadioFrequencyArea:
#          xpath: "./aixm:"
#        VerticalStructure:
#          xpath: "./aixm:"
#    SpecialNavigationSystem:
#      keys:
#      targets:
#        SpecialNavigationStation:
#          xpath: "./aixm:"
#        Procedure:
#          xpath: "./aixm:"
#    StandardInstrumentArrival:
#      keys:
#      targets:
#        ArrivalLeg:
#          xpath: "./aixm:"
#    StandardInstrumentDeparture:
#      keys:
#      targets:
#        NavigationArea:
#          xpath: "./aixm:"
#        DepartureLeg:
#          xpath: "./aixm:"
#    StandardLevelColumn:
#      keys:
#      targets:
#        StandardLevelSector:
#          xpath: "./aixm:"
#    StandardLevelTable:
#      keys:
#      targets:
#        StandardLevelColumn:
#          xpath: "./aixm:"
#    TaxiHoldingPosition:
#      keys:
#      targets:
#        TaxiHoldingPositionLightSystem:
#          xpath: "./aixm:"
#        TaxiHoldingPositionMarking:
#          xpath: "./aixm:"
#    Taxiway:
#      keys:
#      targets:
#        TaxiwayElement:
#          xpath: "./aixm:"
#        GuidanceLine:
#          xpath: "./aixm:"
#        DeicingArea:
#          xpath: "./aixm:"
#        TaxiwayLightSystem:
#          xpath: "./aixm:"
#        TaxiwayMarking:
#          xpath: "./aixm:"
#    TaxiwayElement:
#      keys:
#      targets:
#        TaxiwayMarking:
#          xpath: "./aixm:"
#    TouchDownLiftOff:
#      keys:
#      targets:
#        GuidanceLine:
#          xpath: "./aixm:"
#        TouchDownLiftOffSafeArea:
#          xpath: "./aixm:"
#        TouchDownLiftOffLightSystem:
#          xpath: "./aixm:"
#        TouchDownLiftOffMarking:
#          xpath: "./aixm:"
#        AngleIndication:
#          xpath: "./aixm:"
#        DistanceIndication:
#          xpath: "./aixm:"
#        Navaid:
#          xpath: "./aixm:"
#        DesignatedPoint:
#          xpath: "./aixm:"
#        SignificantPointInAirspace:
#          xpath: "./aixm:"
#        TerminalArrivalArea:
#          xpath: "./aixm:"
#        NavigationArea:
#          xpath: "./aixm:"
#        FinalLeg:
#          xpath: "./aixm:"
#        SafeAltitudeArea:
#          xpath: "./aixm:"
#        ChangeOverPoint:
#          xpath: "./aixm:"
#    Unit:
#      keys:
#      targets:
#        Service:
#          xpath: "./aixm:"
#        VerticalStructure:
#          xpath: "./aixm:"
#    UnplannedHolding:
#      keys:
#      targets:
#        HoldingAssessment:
#          xpath: "./aixm:"
#    VOR:
#      keys:
#      targets:
#        InformationService:
#          xpath: "./aixm:"
#        CheckpointVOR:
#          xpath: "./aixm:"
#    VerticalStructure:
#      keys:
#      targets:
#        AeronauticalGroundLight:
#          xpath: "./aixm:"
#        ObstacleArea:
#          xpath: "./aixm:"
